[package]
name = "gcoder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
reqwest = { version = "0.12.8", features = ["json"] }
roxmltree = "0.19.0"
svg2gcode = "0.3.3"
tokio = { version = "1.40.0", features = ["full"] }
vtracer = "0.6.3"
g-code = "0.5.1"
